/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectogetplay;

import java.awt.Color;
import javax.swing.JOptionPane;

public class JdlEditaUtilizador extends javax.swing.JDialog {
    

    protected Principal pagPrincipal;
    /**
     * Creates new form JdlRegisto
     * @param pagPrincipal
     * @param modal
     */
    public JdlEditaUtilizador(Principal pagPrincipal, boolean modal) {
        
        initComponents();
        this.pagPrincipal=pagPrincipal;
        txtNome.setText(pagPrincipal.getLogged().getName());
        txtEmail.setText(pagPrincipal.getLogged().getEmail());
        
    }
    
    /**
     * Recebe uma String com o e-mail e verifica se o padrão condiz com o descrito
     * na expressão regular. Devolve true se corresponder e false se não corresponder.
     * @param email
     * @return 
     */
    private boolean emailValidation(String email){
    
        String emailReg = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
		+ "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        
        return email.matches(emailReg);
    }
    
    /**
     * Recebe uma String com o nome e verifica se o padrão condiz com o descrito
     * na expressão regular. Devolve true se corresponder e false se não corresponder.
     * @param nome
     * @return 
     */
    private boolean nameValidation(String nome){
    
        String nomeReg = "^[\\p{L} .'-]+$";
        
        return nome.matches(nomeReg);
    }
    
    
    /**
     * Validate the name an email, user auxiliar methods with regex to validate
     * each one individualy. Return boolean with the result.
     * @param name
     * @param email
     * @return 
     */
    private boolean dataValidation(String name, String email){
    
        boolean validated=false;
        
        if(nameValidation(name) && emailValidation(email)){
        
            validated=true;
        }

        return validated;
    }
    
    /**
     * Receives two char[] from password fields and verify if the content
     * matches, return one boolean with the result. 
     * @param pass1
     * @param pass2
     * @return 
     */
    private boolean passwordValidation(char[] pass1, char[] pass2){
    
        boolean validated=false;
        
        String passw1 = String.valueOf(pass1);
        String passw2 = String.valueOf(pass2);
        
        if(passw1.equals(passw2)){
        
            validated = true;
        }
        
        return validated;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPass1 = new javax.swing.JLabel();
        lbPass2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        pwPass1 = new javax.swing.JPasswordField();
        pwPass2 = new javax.swing.JPasswordField();
        btnRegistar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblOldPass = new javax.swing.JLabel();
        txtOldPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImage(null);

        lblNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNome.setText("Name");

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEmail.setText("Email\n");

        lblPass1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPass1.setText("New Password");
        lblPass1.setToolTipText("");

        lbPass2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPass2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPass2.setText("Confirm New Password");
        lbPass2.setToolTipText("");

        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });

        pwPass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwPass1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwPass1FocusLost(evt);
            }
        });

        pwPass2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwPass2FocusLost(evt);
            }
        });

        btnRegistar.setText("Edit");
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancel");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo_100.png"))); // NOI18N
        jLabel1.setToolTipText("");

        lblOldPass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblOldPass.setText("Old Password");

        txtOldPass.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPass2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pwPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblPass1)
                        .addGap(6, 6, 6)
                        .addComponent(pwPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegistar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(lblOldPass))
                            .addComponent(lblNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(txtOldPass))))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOldPass)
                    .addComponent(txtOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblPass1))
                    .addComponent(pwPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPass2)
                    .addComponent(pwPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnRegistar))
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
    }//GEN-LAST:event_txtNomeFocusGained

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
    }//GEN-LAST:event_txtEmailFocusGained

    private void pwPass1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwPass1FocusGained
    }//GEN-LAST:event_pwPass1FocusGained

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed

        String nome = txtNome.getText();
        String email = txtEmail.getText();
        char [] oldPass = txtOldPass.getPassword();
        char[] pass1 = pwPass1.getPassword();
        char[] pass2 = pwPass2.getPassword();
        CodificarMD5 md5= new CodificarMD5();
        
        String oldPassEncr = CodificarMD5.cryptWithMD5(String.valueOf(oldPass));
        
        if(txtNome.getText().isEmpty() || txtEmail.getText().isEmpty() || oldPass.length == 0){
        
            JOptionPane.showMessageDialog(this, "The Fields name, email and old pass are mandatory!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        
        else if(!(pagPrincipal.getLogged().getPassword().equals(oldPassEncr))){
            
            JOptionPane.showMessageDialog(this, "Old password is wrong!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        
        else{
        
            if(pass1.length>0){
                if(nameValidation(nome) && emailValidation(email) && passwordValidation(pass1, pass2)){


                    String passEncrypt = CodificarMD5.cryptWithMD5(String.valueOf(pass2));
                    
                    pagPrincipal.getLogged().setName(nome);
                    pagPrincipal.getLogged().setEmail(email);
                    pagPrincipal.getLogged().setPassword(passEncrypt);
                    
                    //Actualiza o painel com o nome do utilizador

                    pagPrincipal.getPnBaseLogin().remove(pagPrincipal.getPnPesquisa());
                    
                    pagPrincipal.setPnPesquisa(new PnPesquisa(pagPrincipal));
                    pagPrincipal.getPnBaseLogin().add(pagPrincipal.getPnPesquisa());
                    
                    pagPrincipal.getPnBaseLogin().revalidate();
                    pagPrincipal.getPnBaseLogin().repaint();
                    
                    JOptionPane.showMessageDialog(this, "Your data were successfully edited.", "", JOptionPane.INFORMATION_MESSAGE);

                    this.dispose();
                }
                else{

                    JOptionPane.showMessageDialog(this, "Something is wrong, please check the red fields.", "Error!", JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
            
                 if(nameValidation(nome) && emailValidation(email)){

                    pagPrincipal.getLogged().setName(nome);
                    pagPrincipal.getLogged().setEmail(email);
                    
                     //Actualiza o painel com o nome do utilizador

                    pagPrincipal.getPnBaseLogin().remove(pagPrincipal.getPnPesquisa());
                    
                    pagPrincipal.setPnPesquisa(new PnPesquisa(pagPrincipal));
                    pagPrincipal.getPnBaseLogin().add(pagPrincipal.getPnPesquisa());
                    
                    pagPrincipal.getPnBaseLogin().revalidate();
                    pagPrincipal.getPnBaseLogin().repaint();
                    
                    /*
                    //Actualiza o painel com o nome do utilizador
                    pagPrincipal.getPnBaseLogin().remove(pagPrincipal.getPnPesquisa());
                    pagPrincipal.getPnBaseLogin().add(new PnPesquisa(pagPrincipal));
                    pagPrincipal.getPnBaseLogin().revalidate();
                    pagPrincipal.getPnBaseLogin().repaint();
                    */
                    //pnBaseLogin.add(pnPesquisa);
                    
                    JOptionPane.showMessageDialog(this, "Your data were successfully edited.", "", JOptionPane.INFORMATION_MESSAGE);

                    this.dispose();
                }
                else{

                    JOptionPane.showMessageDialog(this, "Something is wrong, please check the red fields.", "Error!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        if(nameValidation(txtNome.getText())){
        
            lblNome.setForeground(Color.black);
        }else{
        
            lblNome.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtNomeFocusLost

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if(emailValidation(txtEmail.getText())){
        
            lblEmail.setForeground(Color.black);
        }
        else{
        
            lblEmail.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void pwPass1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwPass1FocusLost
        if(passwordValidation(pwPass1.getPassword(), pwPass2.getPassword())){
        
            lblPass1.setForeground(Color.black);
            lbPass2.setForeground(Color.black);
        }
        else{
        
            lblPass1.setForeground(Color.red);
            lbPass2.setForeground(Color.red);
            
        }
    }//GEN-LAST:event_pwPass1FocusLost

    private void pwPass2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwPass2FocusLost
        if(passwordValidation(pwPass1.getPassword(), pwPass2.getPassword())){
        
            lblPass1.setForeground(Color.black);
            lbPass2.setForeground(Color.black);
        }
        else{
        
            lblPass1.setForeground(Color.red);
            lbPass2.setForeground(Color.red);
            
        }
    }//GEN-LAST:event_pwPass2FocusLost

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbPass2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblOldPass;
    private javax.swing.JLabel lblPass1;
    private javax.swing.JPasswordField pwPass1;
    private javax.swing.JPasswordField pwPass2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtOldPass;
    // End of variables declaration//GEN-END:variables
}
