/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectogetplay;

import java.util.Arrays;
import javax.swing.JOptionPane;

public class JdlRegisto extends javax.swing.JDialog {
    

    protected Principal pagPrincipal;
    /**
     * Creates new form JdlRegisto
     * @param pagPrincipal
     * @param modal
     */
    public JdlRegisto(Principal pagPrincipal, boolean modal) {
        
        initComponents();
    }

    private boolean validaDados(String nome, String email, char[] pass1, char[] pass2) {

        
        String msg = "";
        boolean preenchido = true, verificacao;
        ValidadorEmail valida = new ValidadorEmail();

        if (nome.isEmpty()) {
            preenchido = false;
            msg += "Nome, ";
        }


        if (!valida.validarEmail(email)) {
            preenchido = false;
            msg +=  "Email, ";
        }

        //verificar password
        boolean verificapass = true;
        if (pass1.length != pass2.length) {
            verificapass = false;
        } else {
            verificapass = Arrays.equals(pass1, pass2);
        }

        if (!verificapass) {
            JOptionPane.showMessageDialog(null, msg, "As Password inseridas não são iguais", JOptionPane.ERROR_MESSAGE);
            //lblPass1AV.setVisible(true);
            //lblPass2AV.setVisible(true);
        }
        if (!preenchido) {
            
            JOptionPane.showMessageDialog(null, msg, "Existem campos nao preenchidos", JOptionPane.ERROR_MESSAGE);
        }

        verificacao = verificapass && preenchido;
        return verificacao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPass1 = new javax.swing.JLabel();
        lbPass2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        pwPass1 = new javax.swing.JPasswordField();
        pwPass2 = new javax.swing.JPasswordField();
        btnRegistar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImage(null);

        lblNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNome.setText("Nome");

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEmail.setText("Email\n");

        lblPass1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPass1.setText("Password");

        lbPass2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPass2.setText("Reescreva a Password");

        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
        });

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
        });

        pwPass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwPass1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwPass1FocusLost(evt);
            }
        });

        btnRegistar.setText("Registar");
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(lblNome)
                .addGap(6, 6, 6)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(lblEmail)
                .addGap(6, 6, 6)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lblPass1)
                .addGap(6, 6, 6)
                .addComponent(pwPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbPass2)
                .addGap(6, 6, 6)
                .addComponent(pwPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(btnRegistar)
                .addGap(30, 30, 30)
                .addComponent(btnCancelar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblNome))
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblEmail))
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblPass1))
                    .addComponent(pwPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbPass2))
                    .addComponent(pwPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistar)
                    .addComponent(btnCancelar)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
    }//GEN-LAST:event_txtNomeFocusGained

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
    }//GEN-LAST:event_txtEmailFocusGained

    private void pwPass1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwPass1FocusGained
    }//GEN-LAST:event_pwPass1FocusGained

    private void pwPass1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwPass1FocusLost
    }//GEN-LAST:event_pwPass1FocusLost

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed


//validar
        String nome = txtNome.getText();
        String email = txtEmail.getText();
        char[] pass1 = pwPass1.getPassword();
        char[] pass2 = pwPass2.getPassword();

        if (validaDados(nome, email, pass1, pass2)) {
           //Convert pass em String
            
           if (!pagPrincipal.getApp().existUser(email)) {

               String password = String.valueOf(pass2);
               //CodificarMD5 md5= new CodificarMD5();
               System.out.println("Password sem encript" + password);
               String passEncriptada=CodificarMD5.cryptWithMD5(password);

               System.out.println("Password encript" + passEncriptada);
               pagPrincipal.getApp().addUser(new User(nome, email, password));
               this.dispose();
               
            } else {
                JOptionPane.showMessageDialog(this, "Já existe um utilizador registado com este e-mail", "!!!", JOptionPane.ERROR_MESSAGE);
           }
        }
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistar;
    private javax.swing.JLabel lbPass2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPass1;
    private javax.swing.JPasswordField pwPass1;
    private javax.swing.JPasswordField pwPass2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
