/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectogetplay;

import java.util.Arrays;
import javax.swing.JOptionPane;

public class JdlRegisto extends javax.swing.JDialog {
    //private ListaUtilizadores utilizadores;

    /**
     * Creates new form JdlRegisto
     */
    public JdlRegisto() {
        
        //utilizadores = new ListaUtilizadores();

        initComponents();
    }

    private boolean validaDados(String nome, String email, char[] pass1, char[] pass2) {

        
        String msg = "";
        boolean preenchido = true, verificacao;
        ValidadorEmail valida = new ValidadorEmail();

        if (nome.isEmpty()) {
            preenchido = false;
            msg += "Nome, ";
        }


        if (!valida.validarEmail(email)) {
            preenchido = false;
            msg +=  "Email, ";
        }

        //verificar password
        boolean verificapass = true;
        if (pass1.length != pass2.length) {
            verificapass = false;
        } else {
            verificapass = Arrays.equals(pass1, pass2);
        }

        if (!verificapass) {
            JOptionPane.showMessageDialog(null, msg, "As Password inseridas não são iguais", JOptionPane.ERROR_MESSAGE);
            //lblPass1AV.setVisible(true);
            //lblPass2AV.setVisible(true);
        }
        if (!preenchido) {
            
            JOptionPane.showMessageDialog(null, msg, "Existem campos nao preenchidos", JOptionPane.ERROR_MESSAGE);
        }

        verificacao = verificapass && preenchido;
        return verificacao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPass1 = new javax.swing.JLabel();
        lbPass2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        pwPass1 = new javax.swing.JPasswordField();
        pwPass2 = new javax.swing.JPasswordField();
        btnRegistar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImage(null);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 6, 0, 6, 0, 6, 0};
        layout.rowHeights = new int[] {0, 6, 0, 6, 0, 6, 0, 6, 0};
        getContentPane().setLayout(layout);

        lblNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNome.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        getContentPane().add(lblNome, gridBagConstraints);

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEmail.setText("Email\n");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        getContentPane().add(lblEmail, gridBagConstraints);

        lblPass1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPass1.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        getContentPane().add(lblPass1, gridBagConstraints);

        lbPass2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPass2.setText("Reescreva a Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        getContentPane().add(lbPass2, gridBagConstraints);

        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        getContentPane().add(txtNome, gridBagConstraints);

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(txtEmail, gridBagConstraints);

        pwPass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwPass1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwPass1FocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(pwPass1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(pwPass2, gridBagConstraints);

        btnRegistar.setText("Registar");
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        getContentPane().add(btnRegistar, gridBagConstraints);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        getContentPane().add(btnCancelar, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
    }//GEN-LAST:event_txtNomeFocusGained

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
    }//GEN-LAST:event_txtEmailFocusGained

    private void pwPass1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwPass1FocusGained
    }//GEN-LAST:event_pwPass1FocusGained

    private void pwPass1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwPass1FocusLost
    }//GEN-LAST:event_pwPass1FocusLost

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
       
/////////////////////////////// 

//validar
        String nome = txtNome.getText();
        String email = txtEmail.getText();
        char[] pass1 = pwPass1.getPassword();
        char[] pass2 = pwPass2.getPassword();

//        if (validaDados(nome, email, pass1, pass2)) {
//            //Convert pass em String
//            //if (!utilizadores.seExiste(login)) {
//
//                String password = String.valueOf(pass2);
//                CodificarMD5 md5= new CodificarMD5();
//                String passEncriptada=md5.cryptWithMD5(password);
//                
//                
//                //encriptacao
//                if (JOptionPane.showConfirmDialog(
//                        null,  "Pretende inserir o Vistante  \n"
//                        +  "Nome  : " + nome + "\n"
//                        +  "Email  : " + email + "\n",
//                        JOptionPane.YES_NO_OPTION)
//                        == JOptionPane.YES_OPTION) {
//                    utilizadores.inserirVisitante(nome, email, password);
//                    dispose();
//                }
//            } else {
//                JOptionPane.showMessageDialog(null,
//                         "Ja existe um Utilizador",
//                         "Login"),
//                        JOptionPane.WARNING_MESSAGE);
//            }
//        }
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistar;
    private javax.swing.JLabel lbPass2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPass1;
    private javax.swing.JPasswordField pwPass1;
    private javax.swing.JPasswordField pwPass2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
