/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectogetplay;

import javax.swing.JOptionPane;

/**
 *
 * @author Aires
 */
public class JdNewPlaylist extends javax.swing.JDialog {

    protected Principal p;

    /**
     * Creates new form JdNewPlaylist
     */
    public JdNewPlaylist(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);//fecha janela mas não a aplicação
        this.setLocationRelativeTo(null);//abre jDialog no centro do ecran
        this.p = (Principal) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomePlaylist = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Playlist");
        setMinimumSize(new java.awt.Dimension(240, 120));
        setPreferredSize(new java.awt.Dimension(240, 120));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNomePlaylist.setMinimumSize(new java.awt.Dimension(140, 25));
        txtNomePlaylist.setPreferredSize(new java.awt.Dimension(140, 25));
        getContentPane().add(txtNomePlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 26, -1, 28));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Name");
        jLabel1.setMaximumSize(new java.awt.Dimension(30, 25));
        jLabel1.setMinimumSize(new java.awt.Dimension(30, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(30, 25));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 28, 50, -1));

        btOk.setText("Ok");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });
        getContentPane().add(btOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 65, -1, -1));

        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 65, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        String nome = txtNomePlaylist.getText();
        
        if(p.getLogged().existPlaylist(nome)){
        
            JOptionPane.showMessageDialog(this, "This playlist already exist, please change the name.",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else{
            Playlist novo = new Playlist(nome);

            p.getLogged().addNewPlaylist(novo);
            p.getPnBaseColuna().removeAll();
            
            p.setPnColuna(new PnColuna(p));
            p.getPnColuna().buildPlaylistListProp(p.getLogged().getPlaylists());
            
            
            p.getPnBaseColuna().add(p.getPnColuna());
            
            p.revalidate();
            p.repaint();
            
            
            //Actualiza a tabela com as playlist´s pessoais
            p.actualizaTabelaMyPlaylist();
            
        }
        this.dispose();

    }//GEN-LAST:event_btOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdNewPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdNewPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdNewPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdNewPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JdNewPlaylist dialog = new JdNewPlaylist(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNomePlaylist;
    // End of variables declaration//GEN-END:variables
}
