/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectogetplay;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Aires
 */
public class PnMyPlayList extends javax.swing.JPanel {

    protected Principal pagPrincipal;
    /**
     * Creates new form PnMusica
     */
    
    /**
     * Creates new form PnMusica
     * @param p
     */
    public PnMyPlayList(Principal p) {
        this.pagPrincipal=p;
        initComponents();
        
    }

    public JLabel getjLabPListDir() {
        return jLabPListDir;
    }

    public void setjLabPListDir(JLabel jLabPListDir) {
        this.jLabPListDir = jLabPListDir;
    }

    public JLabel getjLabPListDir1() {
        return jLabPListDir1;
    }

    public void setjLabPListDir1(JLabel jLabPListDir1) {
        this.jLabPListDir1 = jLabPListDir1;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabPListDir = new javax.swing.JLabel();
        jLabPListDir1 = new javax.swing.JLabel();
        jBNewPlay = new javax.swing.JButton();
        jBEditPlay = new javax.swing.JButton();
        jBRemovePlay = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(830, 100));

        jLabPListDir.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabPListDir.setText("My Playlists");
        jLabPListDir.setToolTipText("");

        try{
            String numPlay="Number of Playlists: ";
            numPlay+=pagPrincipal.getLogged().getPlaylists().size();
            jLabPListDir1.setText(numPlay);
        }catch(Exception e){}
        jLabPListDir1.setToolTipText("");

        jBNewPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Basic-Plus-icon.png"))); // NOI18N
        jBNewPlay.setText("new playlist");
        jBNewPlay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBNewPlay.setContentAreaFilled(false);
        jBNewPlay.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jBNewPlay.setMaximumSize(new java.awt.Dimension(81, 20));
        jBNewPlay.setMinimumSize(new java.awt.Dimension(81, 20));
        jBNewPlay.setPreferredSize(new java.awt.Dimension(81, 20));
        jBNewPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNewPlayActionPerformed(evt);
            }
        });

        jBEditPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Edit-icon.png"))); // NOI18N
        jBEditPlay.setText(" edit");
        jBEditPlay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBEditPlay.setContentAreaFilled(false);
        jBEditPlay.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jBEditPlay.setMaximumSize(new java.awt.Dimension(81, 20));
        jBEditPlay.setMinimumSize(new java.awt.Dimension(81, 20));
        jBEditPlay.setPreferredSize(new java.awt.Dimension(81, 20));

        jBRemovePlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Basic-Minus-icon.png"))); // NOI18N
        jBRemovePlay.setText("remove");
        jBRemovePlay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBRemovePlay.setContentAreaFilled(false);
        jBRemovePlay.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jBRemovePlay.setMaximumSize(new java.awt.Dimension(81, 20));
        jBRemovePlay.setMinimumSize(new java.awt.Dimension(81, 20));
        jBRemovePlay.setPreferredSize(new java.awt.Dimension(81, 20));
        jBRemovePlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemovePlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabPListDir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabPListDir1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 535, Short.MAX_VALUE)
                        .addComponent(jBNewPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jBEditPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jBRemovePlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabPListDir)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabPListDir1)
                    .addComponent(jBNewPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEditPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBRemovePlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBNewPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNewPlayActionPerformed
        JdNewPlaylist jdNewPlaylist = new JdNewPlaylist(pagPrincipal, true);
        jdNewPlaylist.setVisible(true);
    }//GEN-LAST:event_jBNewPlayActionPerformed

    private void jBRemovePlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemovePlayActionPerformed
         int indiceLista = pagPrincipal.getPnColuna().getMyPlaylistsList().getSelectedIndex();
         int indiceTabela = pagPrincipal.getPnTabelaPlayList().getTblPlaylist().getSelectedRow();
         String nomePlay = (String) pagPrincipal.getPnTabelaPlayList().getTblPlaylist().getValueAt(indiceTabela, 0);
            Playlist playl = pagPrincipal.getLogged().findPlaylist(nomePlay);
  
        if (indiceLista == -1 && indiceTabela == -1) {
            JOptionPane.showMessageDialog(this, "Please select one playlist from table or from the \"My Playlists\" list on the left.",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (indiceLista != -1 && indiceTabela != -1) {
            JOptionPane.showMessageDialog(this, "Please select just from table, or from playlist",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
            pagPrincipal.getPnTabelaPlayList().getTblPlaylist().clearSelection();
            pagPrincipal.getPnColuna().getMyPlaylistsList().clearSelection();

        } else {

            if (indiceTabela == -1) {
                pagPrincipal.getLogged().removePlaylist(pagPrincipal.getPnColuna().getPlaylistProp().
                        get(pagPrincipal.getPnColuna().getMyPlaylistsList().getSelectedIndex()));
                pagPrincipal.getPnColuna().buildAllLists();
                pagPrincipal.actualizaTabelaMyPlaylist();
            } else {

                pagPrincipal.getLogged().removePlaylist(playl);
                pagPrincipal.getPnColuna().buildAllLists();
                pagPrincipal.actualizaTabelaMyPlaylist();

            }
        }
    }//GEN-LAST:event_jBRemovePlayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEditPlay;
    private javax.swing.JButton jBNewPlay;
    private javax.swing.JButton jBRemovePlay;
    private javax.swing.JLabel jLabPListDir;
    private javax.swing.JLabel jLabPListDir1;
    // End of variables declaration//GEN-END:variables
}
