/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectogetplay;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aires
 */
public class PnTabelaMusica extends javax.swing.JPanel {

    protected Principal pagPrincipal;

    private DefaultTableModel modelo;
    private ArrayList<Music> dados;
    private int cliqueMusica;
    private Music musicSelecionada;

    //
    /**
     * Creates new form PnTabelaMusica
     */
    public PnTabelaMusica(Principal p) {
        dados = new ArrayList<Music>();
        this.pagPrincipal = p;
        atribuiDados(p.getApp().getMusicsList());
        cliqueMusica=-1;
        initComponents();
    }

    /**
     * Create a new Arralist dados with Object Music, to be used in the Table
     * Model
     *
     * @param musica ArrayList Music
     */
    public void atribuiDados(ArrayList<Music> musica) {
        dados.clear();
        dados = musica;
    }

    public void criaModeloTabela() {
        String[] colunas = new String[]{"Name","Author", "Album",  "Favorite", "Year", "User",""};
        Object[][] dados = new Object[][]{};
        modelo = new DefaultTableModel(dados, colunas);
    }

    public void carregaTabela() {

        for (Music music : dados) {
            
            modelo.addRow(new Object[]{music.getName(), music.getAuthor(), music.getAlbum(), music.isFavorite(), music.getYear(), music.getCreatorEmail(),music.getMusicCode()});
        }
        
    }

    public void adicionaLinha(String name, String album, String artist, int year,String user) {
        int index=pagPrincipal.getApp().musicsList.size();
        int controlo= pagPrincipal.getApp().musicsList.get(index-1).getMusicCode();
        
        Object novo[] = {name, artist, album,  false, year, user, controlo};
        modelo.addRow(novo);
        refresh();
        
    }

    public void refresh() {
        modelo.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblMusic = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(830, 420));
        setPreferredSize(new java.awt.Dimension(830, 420));
        setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setMinimumSize(new java.awt.Dimension(830, 420));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(830, 420));

        criaModeloTabela();
        tblMusic.setAutoCreateRowSorter(true);
        tblMusic.setModel(modelo);
        tblMusic.getColumnModel().getColumn(6).setMinWidth(0);
        tblMusic.getColumnModel().getColumn(6).setMaxWidth(0);
        //tblMusic.getColumnModel().getColumn(6).setPreferredWidth(0);
        carregaTabela();
        tblMusic.setRowHeight(30);
        tblMusic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMusicMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMusic);

        add(jScrollPane2, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void tblMusicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMusicMouseClicked
          int num = (Integer) tblMusic.getValueAt(tblMusic.getSelectedRow(), 6);
          JOptionPane.showMessageDialog(null, "Codigo "+ num);
          cliqueMusica=num;
    }//GEN-LAST:event_tblMusicMouseClicked

    
    
    public Music getMusicSelecionada() {
        return musicSelecionada;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMusic;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the cliqueMusica
     */
    public int getCliqueMusica() {
        return cliqueMusica;
    }
    
    
}
//table.getColumnModel().getColumn(5).setHeaderValue("newHeader");
