/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectogetplay;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Aires
 */
public class PnTabelaPlayList extends javax.swing.JPanel {

    protected Principal pagPrincipal;
    private DefaultTableModel modelo;
    private ArrayList<Playlist> dados;
    
    
    /**
     * Creates new form PnTabelaMusica
     */
    public PnTabelaPlayList(Principal p, ArrayList<Playlist> play) {
        
        this.pagPrincipal=p;
        dados=new ArrayList();
        atribuiDadosPL(play);
        initComponents();
    }

     public void atribuiDadosPL(ArrayList<Playlist> playList) {
        dados.clear();
        dados.addAll(playList);
    }
    public void criaModeloTabelaPL() {
        String[] colunas = new String[]{"Name", "Creation Date", "Size", "Shared","User"};
        Object[][] dados = new Object[][]{};
        modelo = new DefaultTableModel(dados, colunas);
    }

    public void carregaTabelaPL() {
        for (Playlist playlist : dados) {
            modelo.addRow(new Object[]{playlist.getName(), playlist.getdateCreationString(),playlist.getSize(), playlist.getShared()});
        }

    }
    
    public void removeLinha() {
        modelo.removeRow(tblPlaylist.getSelectedRow());
    }

    public JTable getTblPlaylist() {
        return tblPlaylist;
    }

    public void setTblPlaylist(JTable tblPlaylist) {
        this.tblPlaylist = tblPlaylist;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblPlaylist = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(830, 420));
        setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setMinimumSize(new java.awt.Dimension(830, 420));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(830, 420));

        tblPlaylist.setRowHeight(30);
        criaModeloTabelaPL();
        tblPlaylist.setAutoCreateRowSorter(true);
        tblPlaylist.setModel(modelo);
        carregaTabelaPL();
        jScrollPane2.setViewportView(tblPlaylist);

        add(jScrollPane2, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPlaylist;
    // End of variables declaration//GEN-END:variables
}
