/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectogetplay;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.table.TableColumn;

/**
 *
 * @author Aires
 */
public class PnTabelaPlayList extends javax.swing.JPanel {
    private int cliqNome = 0;
    private int cliqCriado = 0;
    private int cliqNmusica = 0;
    protected Principal pagPrincipal;

    
    private TableModelPlaylist modelo;
    private ArrayList<Playlist> dados;
    
    
    /**
     * Creates new form PnTabelaMusica
     */
    public PnTabelaPlayList(Principal p) {
        initComponents();
        this.pagPrincipal=p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlaylist = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(830, 420));
        setLayout(new java.awt.GridBagLayout());

        tblPlaylist.setModel(modelo);
        //dimensões das colunas
        TableColumn column = null;
        for (int i = 0; i < 5; i++) {
            column = tblPlaylist.getColumnModel().getColumn(i);
            column.setPreferredWidth(100);

        }
        tblPlaylist.setRowHeight(50);
        // listener
        tblPlaylist.getTableHeader().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // cliques++;
                int col = tblPlaylist.columnAtPoint(e.getPoint());
                // if (col==0){ modelo.ordenarPorNome();modelo.fireTableDataChanged(); }
                // if (col==2){ modelo.ordenarPorLocalizacao();modelo.fireTableDataChanged(); }
                //if (col==3){ modelo.ordenarPorPontuacao();modelo.fireTableDataChanged(); }
                //if (col==4){ modelo.ordenarPorVisualizacao(cliques);modelo.fireTableDataChanged(); }
            }
        });
        jScrollPane1.setViewportView(tblPlaylist);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 787;
        gridBagConstraints.ipady = 356;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 26, 10);
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPlaylist;
    // End of variables declaration//GEN-END:variables
}
