/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectogetplay;

/**
 *
 * @author Aires
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnFundo = new javax.swing.JPanel();
        pnColuna = new javax.swing.JPanel();
        pnLogin = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        pnInfo = new javax.swing.JPanel();
        pnTabela = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Getplay");
        setMinimumSize(new java.awt.Dimension(1080, 701));
        setPreferredSize(new java.awt.Dimension(1080, 701));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnFundo.setBackground(new java.awt.Color(255, 255, 102));
        pnFundo.setMinimumSize(new java.awt.Dimension(1080, 100));
        pnFundo.setPreferredSize(new java.awt.Dimension(1080, 100));
        pnFundo.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(pnFundo, gridBagConstraints);

        pnColuna.setBackground(new java.awt.Color(102, 255, 102));
        pnColuna.setMinimumSize(new java.awt.Dimension(250, 580));
        pnColuna.setPreferredSize(new java.awt.Dimension(250, 580));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        getContentPane().add(pnColuna, gridBagConstraints);

        pnLogin.setBackground(new java.awt.Color(255, 102, 51));
        pnLogin.setMinimumSize(new java.awt.Dimension(830, 60));
        pnLogin.setPreferredSize(new java.awt.Dimension(830, 60));

        jTextField1.setText("jTextField1");
        pnLogin.add(jTextField1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        getContentPane().add(pnLogin, gridBagConstraints);

        pnInfo.setBackground(new java.awt.Color(102, 102, 255));
        pnInfo.setMinimumSize(new java.awt.Dimension(830, 100));
        pnInfo.setPreferredSize(new java.awt.Dimension(830, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        getContentPane().add(pnInfo, gridBagConstraints);

        pnTabela.setBackground(new java.awt.Color(255, 153, 204));
        pnTabela.setMinimumSize(new java.awt.Dimension(830, 420));
        pnTabela.setPreferredSize(new java.awt.Dimension(830, 420));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        getContentPane().add(pnTabela, gridBagConstraints);

        jMenuBar1.setMaximumSize(new java.awt.Dimension(56, 100));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pnColuna;
    private javax.swing.JPanel pnFundo;
    private javax.swing.JPanel pnInfo;
    private javax.swing.JPanel pnLogin;
    private javax.swing.JPanel pnTabela;
    // End of variables declaration//GEN-END:variables
}
